name: Backend

on:
  push:
    branches:
      - cicd
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          cd server
          docker build . -t warehousesampleregistries.azurecr.io/cicd:${{ github.sha }}
          docker login -u warehousesampleregistries -p bk4TBuR4+EWDbjUYpcPP5wbkT92rUC5+ https://warehousesampleregistries.azurecr.io
          docker push warehousesampleregistries.azurecr.io/cicd:${{ github.sha }}
      - uses: azure/webapps-deploy@v2
        with:
          app-name: "warehousesample"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: "warehousesampleregistries.azurecr.io/cicd:${{ github.sha }}"
