name: Backend

on:
  push:
    branches:
      - github-actions
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: |
          cd Server
          docker build . -t jobloadsstageregistry.azurecr.io/cicd:${{ github.sha }}
          docker login -u jobloadsstageregistry -p VlAT0mx2sN8sUo57tQWUNAwog/hB0dvA https://jobloadsstageregistry.azurecr.io
          docker push jobloadsstageregistry.azurecr.io/cicd:${{ github.sha }}
      - uses: azure/webapps-deploy@v2
        with:
          app-name: "jobloads-stage-web"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: "jobloadsstageregistry.azurecr.io/cicd:${{ github.sha }}"
