# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - warehousesample

on:
  push:
    branches:
      - cicd
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://warehousesampleregistries.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_4eb374e1d0164521944f868deea78259 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2e3d1c6f6c504ccca275801d82aa883b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: warehousesampleregistries.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4eb374e1d0164521944f868deea78259 }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'warehousesample'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_360cf00a587249e2a7a063219da20604 }}
        images: 'warehousesampleregistries.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_4eb374e1d0164521944f868deea78259 }}/mcr.microsoft.com/appsvc/staticsite:${{ github.sha }}'