name: Frontend

on:
  push:
    branches:
      - cicd
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Begin
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install node_modules
        run: |
          cd client
          npm install
      - name: Build static app
        run: |
          cd client
          npm run build
      - name: Install azcopy
        uses: kheiakiyama/install-azcopy-action@v1.0.3

      - uses: kheiakiyama/install-azcopy-action@v1
        with:
          version: "v10"

      - run: azcopy_v10 rm 'https://warehousesamplestorage.blob.core.windows.net/$web?${{ secrets.WAREHOUSE_SAMPLE_STORAGE_WEB_SAS_ACCOUNT_KEY }}' --recursive

      ## Copy the contents of the azure functions
      - uses: kheiakiyama/install-azcopy-action@v1
        with:
          version: "v10"
      - run: azcopy_v10 copy './client/build/*' 'https://warehousesamplestorage.blob.core.windows.net/$web?${{ secrets.WAREHOUSE_SAMPLE_STORAGE_WEB_SAS_ACCOUNT_KEY }}' --recursive
